### ISSUE TITLE
BUG:  darkmode switch transition does not match the rest of the page 

### ISSUE THREAD

**Issue by kevinzunigacuellar** [stackblitz/docs#52]
**Describe the bug**
When switching between dark and light modes, the background color transition of the switch is longer than the rest of the page.

**To Reproduce**
1. Go to [Stackblitz docs](https://developer.stackblitz.com/)
2. Click on the dark/light mode switch multiple times
3. Notice the flash between the background color of the switch with the rest of the page

**Expected behavior**
A smooth transition which duration matches the rest of the page

**Screenshots**

https://user-images.githubusercontent.com/46791833/195650815-16513fbd-a3e9-4ca0-924e-87200f453eb2.mov

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 106

**Smartphone (please complete the following information):**

**Additional context**
- [x] I would like to submit a PR for this 🚀

**Comment by fvsch** [comment]
Hmm I’m not sure this is a problem, personally.

But if it is, it’s a problem that is happening upstream in the Vitepress default theme. Their repo is at https://github.com/vuejs/vitepress/

**Comment by sylwiavargas** [comment]
Thank you, @kevinzunigacuellar !
