### ISSUE TITLE
EXTENSION REQUEST: GitHub Copilot

### ISSUE THREAD

**Issue by raashy** [stackblitz/docs#67]
## Extension details

Please provide us with the details of the extension you want to see added.

* Name: GitHub Copilot
* Id: GitHub.copilot
* Description: Your AI pair programmer
* Version: 1.56.7152
* Publisher: GitHub
* VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot

## Your use case

GitHub Copilot helps me write faster. I use it every day and also have a pro subscription. I would love to use it with StackBlitz!

**Comment by sylwiavargas** [comment]
This is a frequently-requested extension. We have it on our roadmap for the future but not within the next quarter. 
Stay tuned 💙
