### ISSUE TITLE
BUG: Codeflow link results in a broken node_modules install

### ISSUE THREAD

**Issue by wescopeland** [stackblitz/docs#98]
**Describe the bug**
I would like to investigate using Codeflow for an open-source project I maintain. I figured this repo would be a good place to start. However, when clicking the "click this button" link [here](https://github.com/stackblitz/docs#developing-with-stackblitz-codeflow), the project opens but `npm install` unfortunately fails.

**To Reproduce**
1. Go to [this section in the README.md file](https://github.com/stackblitz/docs#developing-with-stackblitz-codeflow).
2. Open the "click this button" link.
3. Observe the terminal.

**Expected behavior**
`npm install` should not fail.

**Screenshots**
![Screen Shot 2023-02-23 at 10 30 05 AM](https://user-images.githubusercontent.com/3984985/220953768-92d6077e-6820-4519-a017-0c05b075b77a.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave

**Comment by samdenty** [comment]
This is due to adblocker blocking gtag.js, we're tracking this issue and thinking of displaying an adblocker disable dialog

**Comment by wescopeland** [comment]
> This is due to adblocker blocking gtag.js, we're tracking this issue and thinking of displaying an adblocker disable dialog

You're right, I would not have guessed this but it makes perfect sense. When disabling Brave's shields, everything runs fine. Some kind of adblocker seems like a reasonable solution. Thanks for your quick reply.
